// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Roll using the value of a standard player condition meter.
 */
@JsonSerialize
public class ActionRollOptionConditionMeter extends ActionRollOption {
    @JsonProperty("condition_meter")
    private ConditionMeterId conditionMeter;

    public ActionRollOptionConditionMeter() {
    }

    /**
     * Getter for conditionMeter.<p>
     */
    public ConditionMeterId getConditionMeter() {
        return conditionMeter;
    }

    /**
     * Setter for conditionMeter.<p>
     */
    public void setConditionMeter(ConditionMeterId conditionMeter) {
        this.conditionMeter = conditionMeter;
    }
}
