// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;

/**
 * Represents a grouping of options in a list of choices.
 */
@JsonSerialize
public class AssetOptionFieldSelectEnhancementChoiceChoiceGroup extends AssetOptionFieldSelectEnhancementChoice {
    @JsonProperty("choices")
    private Map<String, SelectEnhancementFieldChoice> choices;

    @JsonProperty("name")
    private InputLabel name;

    public AssetOptionFieldSelectEnhancementChoiceChoiceGroup() {
    }

    /**
     * Getter for choices.<p>
     */
    public Map<String, SelectEnhancementFieldChoice> getChoices() {
        return choices;
    }

    /**
     * Setter for choices.<p>
     */
    public void setChoices(Map<String, SelectEnhancementFieldChoice> choices) {
        this.choices = choices;
    }

    /**
     * Getter for name.<p>
     * A label for this option group.
     */
    public InputLabel getName() {
        return name;
    }

    /**
     * Setter for name.<p>
     * A label for this option group.
     */
    public void setName(InputLabel name) {
        this.name = name;
    }
}
