// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;
import java.util.Map;

@JsonSerialize
public class Asset {
    @JsonProperty("abilities")
    private List<AssetAbility> abilities;

    @JsonProperty("asset_type")
    private Label assetType;

    @JsonProperty("count_as_impact")
    private Boolean countAsImpact;

    @JsonProperty("id")
    private AssetId id;

    @JsonProperty("name")
    private Label name;

    @JsonProperty("shared")
    private Boolean shared;

    @JsonProperty("source")
    private Source source;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("attachments")
    private AssetAttachment attachments;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("canonical_name")
    private Label canonicalName;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("color")
    private CssColor color;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("controls")
    private Map<String, AssetControlField> controls;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("icon")
    private SvgImageUrl icon;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("options")
    private Map<String, AssetOptionField> options;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("requirement")
    private MarkdownString requirement;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("suggestions")
    private Suggestions suggestions;

    public Asset() {
    }

    /**
     * Getter for abilities.<p>
     */
    public List<AssetAbility> getAbilities() {
        return abilities;
    }

    /**
     * Setter for abilities.<p>
     */
    public void setAbilities(List<AssetAbility> abilities) {
        this.abilities = abilities;
    }

    /**
     * Getter for assetType.<p>
     * A localized category label for this asset. This is the surtitle above the
     * asset's name on the card.
     */
    public Label getAssetType() {
        return assetType;
    }

    /**
     * Setter for assetType.<p>
     * A localized category label for this asset. This is the surtitle above the
     * asset's name on the card.
     */
    public void setAssetType(Label assetType) {
        this.assetType = assetType;
    }

    /**
     * Getter for countAsImpact.<p>
     * If `true`, this asset counts as an impact (Starforged) or a debility
     * (classic Ironsworn).
     */
    public Boolean getCountAsImpact() {
        return countAsImpact;
    }

    /**
     * Setter for countAsImpact.<p>
     * If `true`, this asset counts as an impact (Starforged) or a debility
     * (classic Ironsworn).
     */
    public void setCountAsImpact(Boolean countAsImpact) {
        this.countAsImpact = countAsImpact;
    }

    /**
     * Getter for id.<p>
     * The unique Datasworn ID for this item.
     */
    public AssetId getId() {
        return id;
    }

    /**
     * Setter for id.<p>
     * The unique Datasworn ID for this item.
     */
    public void setId(AssetId id) {
        this.id = id;
    }

    /**
     * Getter for name.<p>
     * The primary name/label for this item.
     */
    public Label getName() {
        return name;
    }

    /**
     * Setter for name.<p>
     * The primary name/label for this item.
     */
    public void setName(Label name) {
        this.name = name;
    }

    /**
     * Getter for shared.<p>
     * Most assets only benefit to their owner, but certain assets (like
     * Starforged's module and command vehicle assets) are shared amongst the
     * player's allies, too.
     */
    public Boolean getShared() {
        return shared;
    }

    /**
     * Setter for shared.<p>
     * Most assets only benefit to their owner, but certain assets (like
     * Starforged's module and command vehicle assets) are shared amongst the
     * player's allies, too.
     */
    public void setShared(Boolean shared) {
        this.shared = shared;
    }

    /**
     * Getter for source.<p>
     * Attribution for the original source (such as a book or website) of this
     * item, including the author and licensing information.
     */
    public Source getSource() {
        return source;
    }

    /**
     * Setter for source.<p>
     * Attribution for the original source (such as a book or website) of this
     * item, including the author and licensing information.
     */
    public void setSource(Source source) {
        this.source = source;
    }

    /**
     * Getter for attachments.<p>
     */
    public AssetAttachment getAttachments() {
        return attachments;
    }

    /**
     * Setter for attachments.<p>
     */
    public void setAttachments(AssetAttachment attachments) {
        this.attachments = attachments;
    }

    /**
     * Getter for canonicalName.<p>
     * The name of this item as it appears on the page in the book, if it's
     * different from `name`.
     */
    public Label getCanonicalName() {
        return canonicalName;
    }

    /**
     * Setter for canonicalName.<p>
     * The name of this item as it appears on the page in the book, if it's
     * different from `name`.
     */
    public void setCanonicalName(Label canonicalName) {
        this.canonicalName = canonicalName;
    }

    /**
     * Getter for color.<p>
     * A thematic color associated with this asset.
     */
    public CssColor getColor() {
        return color;
    }

    /**
     * Setter for color.<p>
     * A thematic color associated with this asset.
     */
    public void setColor(CssColor color) {
        this.color = color;
    }

    /**
     * Getter for controls.<p>
     * Controls are condition meters, clocks, counters, and other asset input
     * fields whose values are expected to change throughout the life of the
     * asset.
     */
    public Map<String, AssetControlField> getControls() {
        return controls;
    }

    /**
     * Setter for controls.<p>
     * Controls are condition meters, clocks, counters, and other asset input
     * fields whose values are expected to change throughout the life of the
     * asset.
     */
    public void setControls(Map<String, AssetControlField> controls) {
        this.controls = controls;
    }

    /**
     * Getter for icon.<p>
     * This asset's icon.
     */
    public SvgImageUrl getIcon() {
        return icon;
    }

    /**
     * Setter for icon.<p>
     * This asset's icon.
     */
    public void setIcon(SvgImageUrl icon) {
        this.icon = icon;
    }

    /**
     * Getter for options.<p>
     * Options are input fields set when the player purchases the asset. They're
     * likely to remain the same through the life of the asset. Typically, they
     * are rendered at the top of the asset card.
     */
    public Map<String, AssetOptionField> getOptions() {
        return options;
    }

    /**
     * Setter for options.<p>
     * Options are input fields set when the player purchases the asset. They're
     * likely to remain the same through the life of the asset. Typically, they
     * are rendered at the top of the asset card.
     */
    public void setOptions(Map<String, AssetOptionField> options) {
        this.options = options;
    }

    /**
     * Getter for requirement.<p>
     * Describes prerequisites for purchasing or using this asset.
     */
    public MarkdownString getRequirement() {
        return requirement;
    }

    /**
     * Setter for requirement.<p>
     * Describes prerequisites for purchasing or using this asset.
     */
    public void setRequirement(MarkdownString requirement) {
        this.requirement = requirement;
    }

    /**
     * Getter for suggestions.<p>
     */
    public Suggestions getSuggestions() {
        return suggestions;
    }

    /**
     * Setter for suggestions.<p>
     */
    public void setSuggestions(Suggestions suggestions) {
        this.suggestions = suggestions;
    }
}
