// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A delve site theme card.
 */
public enum DelveSiteThemeCardType {
    @JsonProperty("theme")
    THEME,
}
