// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum MoveRollType {
    @JsonProperty("action_roll")
    ACTION_ROLL,

    @JsonProperty("no_roll")
    NO_ROLL,

    @JsonProperty("progress_roll")
    PROGRESS_ROLL,

    @JsonProperty("special_track")
    SPECIAL_TRACK,
}
