// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * An object that describes changes to a move. These changes should be applied
 * recursively, altering only the specified properties; enhanced arrays should
 * be concatencated with the original array value.
 */
@JsonSerialize
public class MoveEnhancementNoRoll extends MoveEnhancement {
    @JsonProperty("enhances")
    private List<MoveIdWildcard> enhances;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("trigger")
    private TriggerNoRollEnhancement trigger;

    public MoveEnhancementNoRoll() {
    }

    /**
     * Getter for enhances.<p>
     */
    public List<MoveIdWildcard> getEnhances() {
        return enhances;
    }

    /**
     * Setter for enhances.<p>
     */
    public void setEnhances(List<MoveIdWildcard> enhances) {
        this.enhances = enhances;
    }

    /**
     * Getter for trigger.<p>
     */
    public TriggerNoRollEnhancement getTrigger() {
        return trigger;
    }

    /**
     * Setter for trigger.<p>
     */
    public void setTrigger(TriggerNoRollEnhancement trigger) {
        this.trigger = trigger;
    }
}
