// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A standalone localized description for each move outcome (miss, weak hit,
 * or strong hit). This is for for e.g. VTT implementations, where it's often
 * useful to display only the rules text relevant to a roll result.
 * 
 *   This often requires light editorialization to create text that can stand
 * alone without reference to the rest of the move. For example, 'as above'
 * (in reference to another move outcome) shouldn't be used here; instead, the
 * relevant text should be repeated.
 */
@JsonSerialize
public class MoveOutcomes {
    @JsonProperty("miss")
    private MoveOutcome miss;

    @JsonProperty("strong_hit")
    private MoveOutcome strongHit;

    @JsonProperty("weak_hit")
    private MoveOutcome weakHit;

    public MoveOutcomes() {
    }

    /**
     * Getter for miss.<p>
     */
    public MoveOutcome getMiss() {
        return miss;
    }

    /**
     * Setter for miss.<p>
     */
    public void setMiss(MoveOutcome miss) {
        this.miss = miss;
    }

    /**
     * Getter for strongHit.<p>
     */
    public MoveOutcome getStrongHit() {
        return strongHit;
    }

    /**
     * Setter for strongHit.<p>
     */
    public void setStrongHit(MoveOutcome strongHit) {
        this.strongHit = strongHit;
    }

    /**
     * Getter for weakHit.<p>
     */
    public MoveOutcome getWeakHit() {
        return weakHit;
    }

    /**
     * Setter for weakHit.<p>
     */
    public void setWeakHit(MoveOutcome weakHit) {
        this.weakHit = weakHit;
    }
}
