// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A wildcarded ID that can be used to match multiple Npcs.
 */
public class NpcIdWildcard {
    @JsonValue
    private String value;

    public NpcIdWildcard() {
    }

    @JsonCreator
    public NpcIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
