// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A localized category label describing the nature of this NPC.
 * 
 * In Ironsworn classic, this is probably the singular form of the parent
 * collection's name.
 * 
 * For Starforged, see the table on p. 258 for examples.
 */
public class NpcNature {
    @JsonValue
    private Label value;

    public NpcNature() {
    }

    @JsonCreator
    public NpcNature(Label value) {
        this.value = value;
    }

    public Label getValue() {
        return value;
    }

    public void setValue(Label value) {
        this.value = value;
    }
}
