// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A unique ID for a NpcVariant.
 */
public class NpcVariantId {
    @JsonValue
    private String value;

    public NpcVariantId() {
    }

    @JsonCreator
    public NpcVariantId(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
