// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Oracle table wildcards can also use '**' to represent any number of
 * collection levels in the oracle tree.
 */
public class OracleTableIdWildcard {
    @JsonValue
    private String value;

    public OracleTableIdWildcard() {
    }

    @JsonCreator
    public OracleTableIdWildcard(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }
}
