// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;

/**
 * Describes the features of a type of progress track.
 */
@JsonSerialize
public class ProgressTrackTypeInfo {
    @JsonProperty("category")
    private Label category;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonProperty("controls")
    private Map<String, Object> controls;

    public ProgressTrackTypeInfo() {
    }

    /**
     * Getter for category.<p>
     * A category label for progress tracks of this type.
     */
    public Label getCategory() {
        return category;
    }

    /**
     * Setter for category.<p>
     * A category label for progress tracks of this type.
     */
    public void setCategory(Label category) {
        this.category = category;
    }

    /**
     * Getter for controls.<p>
     */
    public Map<String, Object> getControls() {
        return controls;
    }

    /**
     * Setter for controls.<p>
     */
    public void setControls(Map<String, Object> controls) {
        this.controls = controls;
    }
}
