// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A reference to the value of an attached asset option.
 */
@JsonSerialize
public class RollableValueAttachedAssetOption extends RollableValue {
    @JsonProperty("option")
    private DictKey option;

    public RollableValueAttachedAssetOption() {
    }

    /**
     * Getter for option.<p>
     * The dictionary key of the asset option field.
     */
    public DictKey getOption() {
        return option;
    }

    /**
     * Setter for option.<p>
     * The dictionary key of the asset option field.
     */
    public void setOption(DictKey option) {
        this.option = option;
    }
}
