// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A reference to the value of a standard player condition meter.
 */
@JsonSerialize
public class RollableValueConditionMeter extends RollableValue {
    @JsonProperty("condition_meter")
    private ConditionMeterKey conditionMeter;

    public RollableValueConditionMeter() {
    }

    /**
     * Getter for conditionMeter.<p>
     */
    public ConditionMeterKey getConditionMeter() {
        return conditionMeter;
    }

    /**
     * Setter for conditionMeter.<p>
     */
    public void setConditionMeter(ConditionMeterKey conditionMeter) {
        this.conditionMeter = conditionMeter;
    }
}
