// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * Represents an option in a list of choices.
 */
@JsonSerialize
public class SelectValueFieldChoiceStat extends SelectValueFieldChoice {
    @JsonProperty("choice_type")
    private SelectValueFieldChoiceStatChoiceType choiceType;

    @JsonProperty("label")
    private InputLabel label;

    @JsonProperty("stat")
    private StatKey stat;

    public SelectValueFieldChoiceStat() {
    }

    /**
     * Getter for choiceType.<p>
     */
    public SelectValueFieldChoiceStatChoiceType getChoiceType() {
        return choiceType;
    }

    /**
     * Setter for choiceType.<p>
     */
    public void setChoiceType(SelectValueFieldChoiceStatChoiceType choiceType) {
        this.choiceType = choiceType;
    }

    /**
     * Getter for label.<p>
     */
    public InputLabel getLabel() {
        return label;
    }

    /**
     * Setter for label.<p>
     */
    public void setLabel(InputLabel label) {
        this.label = label;
    }

    /**
     * Getter for stat.<p>
     */
    public StatKey getStat() {
        return stat;
    }

    /**
     * Setter for stat.<p>
     */
    public void setStat(StatKey stat) {
        this.stat = stat;
    }
}
