// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * Represents an option in a list of choices.
 */
@JsonSerialize
public class SelectValueFieldChoiceAssetOption extends SelectValueFieldChoice {
    @JsonProperty("assets")
    private List<AssetIdWildcard> assets;

    @JsonProperty("choice_type")
    private SelectValueFieldChoiceAssetOptionChoiceType choiceType;

    @JsonProperty("label")
    private InputLabel label;

    @JsonProperty("option")
    private DictKey option;

    public SelectValueFieldChoiceAssetOption() {
    }

    /**
     * Getter for assets.<p>
     */
    public List<AssetIdWildcard> getAssets() {
        return assets;
    }

    /**
     * Setter for assets.<p>
     */
    public void setAssets(List<AssetIdWildcard> assets) {
        this.assets = assets;
    }

    /**
     * Getter for choiceType.<p>
     */
    public SelectValueFieldChoiceAssetOptionChoiceType getChoiceType() {
        return choiceType;
    }

    /**
     * Setter for choiceType.<p>
     */
    public void setChoiceType(SelectValueFieldChoiceAssetOptionChoiceType choiceType) {
        this.choiceType = choiceType;
    }

    /**
     * Getter for label.<p>
     */
    public InputLabel getLabel() {
        return label;
    }

    /**
     * Setter for label.<p>
     */
    public void setLabel(InputLabel label) {
        this.label = label;
    }

    /**
     * Getter for option.<p>
     * The dictionary key of the asset option field.
     */
    public DictKey getOption() {
        return option;
    }

    /**
     * Setter for option.<p>
     * The dictionary key of the asset option field.
     */
    public void setOption(DictKey option) {
        this.option = option;
    }
}
