// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * Represents an option in a list of choices.
 */
@JsonSerialize
public class SelectValueFieldChoiceAssetControl extends SelectValueFieldChoice {
    @JsonProperty("assets")
    private List<AssetIdWildcard> assets;

    @JsonProperty("choice_type")
    private SelectValueFieldChoiceAssetControlChoiceType choiceType;

    @JsonProperty("control")
    private DictKey control;

    @JsonProperty("label")
    private InputLabel label;

    public SelectValueFieldChoiceAssetControl() {
    }

    /**
     * Getter for assets.<p>
     */
    public List<AssetIdWildcard> getAssets() {
        return assets;
    }

    /**
     * Setter for assets.<p>
     */
    public void setAssets(List<AssetIdWildcard> assets) {
        this.assets = assets;
    }

    /**
     * Getter for choiceType.<p>
     */
    public SelectValueFieldChoiceAssetControlChoiceType getChoiceType() {
        return choiceType;
    }

    /**
     * Setter for choiceType.<p>
     */
    public void setChoiceType(SelectValueFieldChoiceAssetControlChoiceType choiceType) {
        this.choiceType = choiceType;
    }

    /**
     * Getter for control.<p>
     * The dictionary key of the asset control field.
     */
    public DictKey getControl() {
        return control;
    }

    /**
     * Setter for control.<p>
     * The dictionary key of the asset control field.
     */
    public void setControl(DictKey control) {
        this.control = control;
    }

    /**
     * Getter for label.<p>
     */
    public InputLabel getLabel() {
        return label;
    }

    /**
     * Setter for label.<p>
     */
    public void setLabel(InputLabel label) {
        this.label = label;
    }
}
