// Code generated by jtd-codegen for Java + Jackson v0.2.1

package Datasworn;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.List;

/**
 * Describes trigger conditions for a move that makes an action roll.
 */
@JsonSerialize
public class TriggerActionRoll {
    @JsonProperty("conditions")
    private List<TriggerActionRollCondition> conditions;

    @JsonProperty("text")
    private MarkdownString text;

    public TriggerActionRoll() {
    }

    /**
     * Getter for conditions.<p>
     * Specific conditions that qualify for this trigger.
     */
    public List<TriggerActionRollCondition> getConditions() {
        return conditions;
    }

    /**
     * Setter for conditions.<p>
     * Specific conditions that qualify for this trigger.
     */
    public void setConditions(List<TriggerActionRollCondition> conditions) {
        this.conditions = conditions;
    }

    /**
     * Getter for text.<p>
     * A markdown string containing the primary trigger text for this move.
     * 
     * Secondary trigger text (for specific stats or uses of an asset ability)
     * may be described in individual trigger conditions.
     */
    public MarkdownString getText() {
        return text;
    }

    /**
     * Setter for text.<p>
     * A markdown string containing the primary trigger text for this move.
     * 
     * Secondary trigger text (for specific stats or uses of an asset ability)
     * may be described in individual trigger conditions.
     */
    public void setText(MarkdownString text) {
        this.text = text;
    }
}
