// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Roll using the value of an attached asset control. For example, a
    /// Module asset could use this to roll using the `integrity` control of an
    /// attached Vehicle.
    /// </summary>
    public class ActionRollOptionAttachedAssetControl : ActionRollOption
    {
        [JsonPropertyName("using")]
        public string Using { get => "attached_asset_control"; }

        /// <summary>
        /// The dictionary key of the asset control field.
        /// </summary>
        [JsonPropertyName("control")]
        public DictKey Control { get; set; }
    }
}
