// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Roll using a standard player character stat.
    /// </summary>
    public class ActionRollOptionStat : ActionRollOption
    {
        [JsonPropertyName("using")]
        public string Using { get => "stat"; }

        [JsonPropertyName("stat")]
        public StatId Stat { get; set; }
    }
}
