// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents a checkbox.
    /// </summary>
    public class AssetConditionMeterControlFieldCheckbox : AssetConditionMeterControlField
    {
        [JsonPropertyName("field_type")]
        public string FieldType { get => "checkbox"; }

        /// <summary>
        /// Does this field disable the asset when its value is set to `true`?
        /// </summary>
        [JsonPropertyName("disables_asset")]
        public bool DisablesAsset { get; set; }

        /// <summary>
        /// The unique Datasworn ID for this item.
        /// </summary>
        [JsonPropertyName("id")]
        public AssetConditionMeterControlFieldId Id { get; set; }

        /// <summary>
        /// Does this field count as an impact (Starforged) or debility
        /// (Ironsworn classic) when its value is set to `true`?
        /// </summary>
        [JsonPropertyName("is_impact")]
        public bool IsImpact { get; set; }

        [JsonPropertyName("label")]
        public InputLabel Label { get; set; }

        /// <summary>
        /// Is the box checked?
        /// </summary>
        [JsonPropertyName("value")]
        public bool Value { get; set; }
    }
}
