// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents a list of mutually exclusive choices.
    /// </summary>
    public class AssetOptionFieldSelectValue : AssetOptionField
    {
        [JsonPropertyName("field_type")]
        public string FieldType { get => "select_value"; }

        [JsonPropertyName("choices")]
        public IDictionary<string, AssetOptionFieldSelectValueChoice> Choices { get; set; }

        /// <summary>
        /// The unique Datasworn ID for this item.
        /// </summary>
        [JsonPropertyName("id")]
        public AssetOptionFieldId Id { get; set; }

        [JsonPropertyName("label")]
        public InputLabel Label { get; set; }

        /// <summary>
        /// The key of the currently selected choice from the `choices`
        /// property, or `null` if none is selected.
        /// </summary>
        [JsonPropertyName("value")]
        public DictKey Value { get; set; }
    }
}
