// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an input that accepts plain text.
    /// </summary>
    public class AssetOptionFieldText : AssetOptionField
    {
        [JsonPropertyName("field_type")]
        public string FieldType { get => "text"; }

        /// <summary>
        /// The unique Datasworn ID for this item.
        /// </summary>
        [JsonPropertyName("id")]
        public AssetOptionFieldId Id { get; set; }

        [JsonPropertyName("label")]
        public InputLabel Label { get; set; }

        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// An icon associated with this input.
        /// </summary>
        [JsonPropertyName("icon")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public SvgImageUrl? Icon { get; set; }
    }
}
