// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetOptionFieldJsonConverter))]
    public abstract class AssetOptionField
    {
    }

    public class AssetOptionFieldJsonConverter : JsonConverter<AssetOptionField>
    {
        public override AssetOptionField Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var readerCopy = reader;
            var tagValue = JsonDocument.ParseValue(ref reader).RootElement.GetProperty("field_type").GetString();

            switch (tagValue)
            {
                case "select_enhancement":
                    return JsonSerializer.Deserialize<AssetOptionFieldSelectEnhancement>(ref readerCopy, options);
                case "select_stat":
                    return JsonSerializer.Deserialize<AssetOptionFieldSelectStat>(ref readerCopy, options);
                case "text":
                    return JsonSerializer.Deserialize<AssetOptionFieldText>(ref readerCopy, options);
                default:
                    throw new ArgumentException(String.Format("Bad FieldType value: {0}", tagValue));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetOptionField value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
        }
    }
}
