// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetOptionFieldSelectValueChoiceAssetControlOptionTypeJsonConverter))]
    public enum AssetOptionFieldSelectValueChoiceAssetControlOptionType
    {
        Option,
    }
    public class AssetOptionFieldSelectValueChoiceAssetControlOptionTypeJsonConverter : JsonConverter<AssetOptionFieldSelectValueChoiceAssetControlOptionType>
    {
        public override AssetOptionFieldSelectValueChoiceAssetControlOptionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "option":
                    return AssetOptionFieldSelectValueChoiceAssetControlOptionType.Option;
                default:
                    throw new ArgumentException(String.Format("Bad AssetOptionFieldSelectValueChoiceAssetControlOptionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetOptionFieldSelectValueChoiceAssetControlOptionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetOptionFieldSelectValueChoiceAssetControlOptionType.Option:
                    JsonSerializer.Serialize<string>(writer, "option", options);
                    return;
            }
        }
    }
}
