// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an option in a list of choices.
    /// </summary>
    public class AssetOptionFieldSelectValueChoiceAssetOption : AssetOptionFieldSelectValueChoice
    {
        [JsonPropertyName("using")]
        public string Using { get => "asset_option"; }

        [JsonPropertyName("assets")]
        public IList<AssetIdWildcard> Assets { get; set; }

        [JsonPropertyName("label")]
        public Label Label { get; set; }

        /// <summary>
        /// The dictionary key of the asset option field.
        /// </summary>
        [JsonPropertyName("option")]
        public DictKey Option { get; set; }

        [JsonPropertyName("option_type")]
        public AssetOptionFieldSelectValueChoiceAssetOptionOptionType OptionType { get; set; }
    }
}
