// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an option in a list of choices.
    /// </summary>
    public class AssetOptionFieldSelectValueChoiceAttachedAssetControl : AssetOptionFieldSelectValueChoice
    {
        [JsonPropertyName("using")]
        public string Using { get => "attached_asset_control"; }

        /// <summary>
        /// The dictionary key of the asset control field.
        /// </summary>
        [JsonPropertyName("control")]
        public DictKey Control { get; set; }

        [JsonPropertyName("label")]
        public Label Label { get; set; }

        [JsonPropertyName("option_type")]
        public AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType OptionType { get; set; }
    }
}
