// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionTypeJsonConverter))]
    public enum AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType
    {
        Option,
    }
    public class AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionTypeJsonConverter : JsonConverter<AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType>
    {
        public override AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "option":
                    return AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType.Option;
                default:
                    throw new ArgumentException(String.Format("Bad AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetOptionFieldSelectValueChoiceAttachedAssetControlOptionType.Option:
                    JsonSerializer.Serialize<string>(writer, "option", options);
                    return;
            }
        }
    }
}
