// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(AssetOptionFieldSelectValueChoiceAssetOptionOptionTypeJsonConverter))]
    public enum AssetOptionFieldSelectValueChoiceAssetOptionOptionType
    {
        Option,
    }
    public class AssetOptionFieldSelectValueChoiceAssetOptionOptionTypeJsonConverter : JsonConverter<AssetOptionFieldSelectValueChoiceAssetOptionOptionType>
    {
        public override AssetOptionFieldSelectValueChoiceAssetOptionOptionType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "option":
                    return AssetOptionFieldSelectValueChoiceAssetOptionOptionType.Option;
                default:
                    throw new ArgumentException(String.Format("Bad AssetOptionFieldSelectValueChoiceAssetOptionOptionType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, AssetOptionFieldSelectValueChoiceAssetOptionOptionType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AssetOptionFieldSelectValueChoiceAssetOptionOptionType.Option:
                    JsonSerializer.Serialize<string>(writer, "option", options);
                    return;
            }
        }
    }
}
