// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class ConditionMeterRule
    {
        [JsonPropertyName("description")]
        public MarkdownString Description { get; set; }

        /// <summary>
        /// The maximum value of this meter.
        /// </summary>
        [JsonPropertyName("max")]
        public short Max { get; set; }

        /// <summary>
        /// The minimum value of this meter.
        /// </summary>
        [JsonPropertyName("min")]
        public short Min { get; set; }

        /// <summary>
        /// A label for this input. In some contexts it may be undesirable
        /// to render this text, but it should always be exposed to assistive
        /// technology (e.g. with `aria-label` in HTML).
        /// </summary>
        [JsonPropertyName("name")]
        public Label Name { get; set; }

        [JsonPropertyName("shared")]
        public bool Shared { get; set; }
    }
}
