// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class DelveSiteDenizen
    {
        [JsonPropertyName("frequency")]
        public DelveSiteDenizenFrequency Frequency { get; set; }

        [JsonPropertyName("id")]
        public DelveSiteDenizenId Id { get; set; }

        [JsonPropertyName("max")]
        public short Max { get; set; }

        [JsonPropertyName("min")]
        public short Min { get; set; }

        [JsonPropertyName("name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Label? Name { get; set; }

        /// <summary>
        /// The ID of the relevant NPC entry, if one is specified.
        /// </summary>
        [JsonPropertyName("npc")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public NpcId? Npc { get; set; }
    }
}
