// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// The ID of a Datasworn package that enhances another Datasworn package,
    /// and relies on another package to provide its ruleset.
    /// </summary>
    [JsonConverter(typeof(ExpansionIdJsonConverter))]
    public class ExpansionId
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public string Value { get; set; }
    }

    public class ExpansionIdJsonConverter : JsonConverter<ExpansionId>
    {
        public override ExpansionId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new ExpansionId { Value = JsonSerializer.Deserialize<string>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, ExpansionId value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<string>(writer, value.Value, options);
        }
    }
}
