// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class NpcVariant
    {
        [JsonPropertyName("description")]
        public MarkdownString Description { get; set; }

        [JsonPropertyName("id")]
        public NpcVariantId Id { get; set; }

        [JsonPropertyName("name")]
        public Label Name { get; set; }

        [JsonPropertyName("nature")]
        public NpcNature Nature { get; set; }

        [JsonPropertyName("rank")]
        public ChallengeRank Rank { get; set; }

        [JsonPropertyName("summary")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public MarkdownString? Summary { get; set; }
    }
}
