// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class OracleTableRenderingColumn : OracleTableRendering
    {
        [JsonPropertyName("style")]
        public string Style { get => "column"; }
    }
}
