// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    public class OracleTableColumn
    {
        [JsonPropertyName("content_type")]
        public OracleTableColumnContentKey ContentType { get; set; }

        /// <summary>
        /// The column's header text.
        /// </summary>
        [JsonPropertyName("label")]
        public Label Label { get; set; }

        /// <summary>
        /// The thematic color for this column.
        /// </summary>
        [JsonPropertyName("color")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public CssColor? Color { get; set; }
    }
}
