// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Describes the presentation of this oracle collection, which might
    /// represent a group of separate tables, or a single table with additional
    /// columns.
    /// </summary>
    [JsonConverter(typeof(OracleCollectionRenderingJsonConverter))]
    public abstract class OracleCollectionRendering
    {
    }

    public class OracleCollectionRenderingJsonConverter : JsonConverter<OracleCollectionRendering>
    {
        public override OracleCollectionRendering Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var readerCopy = reader;
            var tagValue = JsonDocument.ParseValue(ref reader).RootElement.GetProperty("style").GetString();

            switch (tagValue)
            {
                case "multi_table":
                    return JsonSerializer.Deserialize<OracleCollectionRenderingMultiTable>(ref readerCopy, options);
                default:
                    throw new ArgumentException(String.Format("Bad Style value: {0}", tagValue));
            }
        }

        public override void Write(Utf8JsonWriter writer, OracleCollectionRendering value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
        }
    }
}
