// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(PartOfSpeechJsonConverter))]
    public enum PartOfSpeech
    {
        Adjective,

        AdjunctCommonNoun,

        AdjunctProperNoun,

        AttributiveVerb,

        CommonNoun,

        Gerund,

        ProperNoun,

        Verb,
    }
    public class PartOfSpeechJsonConverter : JsonConverter<PartOfSpeech>
    {
        public override PartOfSpeech Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "adjective":
                    return PartOfSpeech.Adjective;
                case "adjunct_common_noun":
                    return PartOfSpeech.AdjunctCommonNoun;
                case "adjunct_proper_noun":
                    return PartOfSpeech.AdjunctProperNoun;
                case "attributive_verb":
                    return PartOfSpeech.AttributiveVerb;
                case "common_noun":
                    return PartOfSpeech.CommonNoun;
                case "gerund":
                    return PartOfSpeech.Gerund;
                case "proper_noun":
                    return PartOfSpeech.ProperNoun;
                case "verb":
                    return PartOfSpeech.Verb;
                default:
                    throw new ArgumentException(String.Format("Bad PartOfSpeech value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, PartOfSpeech value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case PartOfSpeech.Adjective:
                    JsonSerializer.Serialize<string>(writer, "adjective", options);
                    return;
                case PartOfSpeech.AdjunctCommonNoun:
                    JsonSerializer.Serialize<string>(writer, "adjunct_common_noun", options);
                    return;
                case PartOfSpeech.AdjunctProperNoun:
                    JsonSerializer.Serialize<string>(writer, "adjunct_proper_noun", options);
                    return;
                case PartOfSpeech.AttributiveVerb:
                    JsonSerializer.Serialize<string>(writer, "attributive_verb", options);
                    return;
                case PartOfSpeech.CommonNoun:
                    JsonSerializer.Serialize<string>(writer, "common_noun", options);
                    return;
                case PartOfSpeech.Gerund:
                    JsonSerializer.Serialize<string>(writer, "gerund", options);
                    return;
                case PartOfSpeech.ProperNoun:
                    JsonSerializer.Serialize<string>(writer, "proper_noun", options);
                    return;
                case PartOfSpeech.Verb:
                    JsonSerializer.Serialize<string>(writer, "verb", options);
                    return;
            }
        }
    }
}
