// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(ProgressRollOptionUsingJsonConverter))]
    public enum ProgressRollOptionUsing
    {
        ProgressTrack,
    }
    public class ProgressRollOptionUsingJsonConverter : JsonConverter<ProgressRollOptionUsing>
    {
        public override ProgressRollOptionUsing Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "progress_track":
                    return ProgressRollOptionUsing.ProgressTrack;
                default:
                    throw new ArgumentException(String.Format("Bad ProgressRollOptionUsing value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, ProgressRollOptionUsing value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ProgressRollOptionUsing.ProgressTrack:
                    JsonSerializer.Serialize<string>(writer, "progress_track", options);
                    return;
            }
        }
    }
}
