// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Describes game rules compatible with the Ironsworn tabletop role-playing
    /// game by Shawn Tomkin.
    /// </summary>
    [JsonConverter(typeof(RulesPackageJsonConverter))]
    public abstract class RulesPackage
    {
    }

    public class RulesPackageJsonConverter : JsonConverter<RulesPackage>
    {
        public override RulesPackage Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var readerCopy = reader;
            var tagValue = JsonDocument.ParseValue(ref reader).RootElement.GetProperty("package_type").GetString();

            switch (tagValue)
            {
                case "expansion":
                    return JsonSerializer.Deserialize<RulesPackageExpansion>(ref readerCopy, options);
                case "ruleset":
                    return JsonSerializer.Deserialize<RulesPackageRuleset>(ref readerCopy, options);
                default:
                    throw new ArgumentException(String.Format("Bad PackageType value: {0}", tagValue));
            }
        }

        public override void Write(Utf8JsonWriter writer, RulesPackage value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
        }
    }
}
