// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SelectValueFieldChoiceJsonConverter))]
    public abstract class SelectValueFieldChoice
    {
    }

    public class SelectValueFieldChoiceJsonConverter : JsonConverter<SelectValueFieldChoice>
    {
        public override SelectValueFieldChoice Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var readerCopy = reader;
            var tagValue = JsonDocument.ParseValue(ref reader).RootElement.GetProperty("using").GetString();

            switch (tagValue)
            {
                case "asset_control":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceAssetControl>(ref readerCopy, options);
                case "asset_option":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceAssetOption>(ref readerCopy, options);
                case "attached_asset_control":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceAttachedAssetControl>(ref readerCopy, options);
                case "attached_asset_option":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceAttachedAssetOption>(ref readerCopy, options);
                case "condition_meter":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceConditionMeter>(ref readerCopy, options);
                case "custom":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceCustom>(ref readerCopy, options);
                case "stat":
                    return JsonSerializer.Deserialize<SelectValueFieldChoiceStat>(ref readerCopy, options);
                default:
                    throw new ArgumentException(String.Format("Bad Using value: {0}", tagValue));
            }
        }

        public override void Write(Utf8JsonWriter writer, SelectValueFieldChoice value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize(writer, value, value.GetType(), options);
        }
    }
}
