// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SelectValueFieldChoiceAssetOptionChoiceTypeJsonConverter))]
    public enum SelectValueFieldChoiceAssetOptionChoiceType
    {
        Choice,
    }
    public class SelectValueFieldChoiceAssetOptionChoiceTypeJsonConverter : JsonConverter<SelectValueFieldChoiceAssetOptionChoiceType>
    {
        public override SelectValueFieldChoiceAssetOptionChoiceType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "choice":
                    return SelectValueFieldChoiceAssetOptionChoiceType.Choice;
                default:
                    throw new ArgumentException(String.Format("Bad SelectValueFieldChoiceAssetOptionChoiceType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, SelectValueFieldChoiceAssetOptionChoiceType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case SelectValueFieldChoiceAssetOptionChoiceType.Choice:
                    JsonSerializer.Serialize<string>(writer, "choice", options);
                    return;
            }
        }
    }
}
