// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an option in a list of choices.
    /// </summary>
    public class SelectEnhancementFieldChoice
    {
        [JsonPropertyName("choice_type")]
        public SelectEnhancementFieldChoiceChoiceType ChoiceType { get; set; }

        [JsonPropertyName("label")]
        public InputLabel Label { get; set; }

        [JsonPropertyName("enhance_asset")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AssetEnhancement? EnhanceAsset { get; set; }

        [JsonPropertyName("enhance_moves")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public IList<MoveEnhancement> EnhanceMoves { get; set; }
    }
}
