// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Represents an option in a list of choices.
    /// </summary>
    public class SelectValueFieldChoiceConditionMeter : SelectValueFieldChoice
    {
        [JsonPropertyName("using")]
        public string Using { get => "condition_meter"; }

        [JsonPropertyName("choice_type")]
        public SelectValueFieldChoiceConditionMeterChoiceType ChoiceType { get; set; }

        [JsonPropertyName("condition_meter")]
        public ConditionMeterKey ConditionMeter { get; set; }

        [JsonPropertyName("label")]
        public InputLabel Label { get; set; }
    }
}
