// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SelectValueFieldChoiceAssetControlChoiceTypeJsonConverter))]
    public enum SelectValueFieldChoiceAssetControlChoiceType
    {
        Choice,
    }
    public class SelectValueFieldChoiceAssetControlChoiceTypeJsonConverter : JsonConverter<SelectValueFieldChoiceAssetControlChoiceType>
    {
        public override SelectValueFieldChoiceAssetControlChoiceType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "choice":
                    return SelectValueFieldChoiceAssetControlChoiceType.Choice;
                default:
                    throw new ArgumentException(String.Format("Bad SelectValueFieldChoiceAssetControlChoiceType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, SelectValueFieldChoiceAssetControlChoiceType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case SelectValueFieldChoiceAssetControlChoiceType.Choice:
                    JsonSerializer.Serialize<string>(writer, "choice", options);
                    return;
            }
        }
    }
}
