// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Datasworn
{
    [JsonConverter(typeof(SelectValueFieldChoiceConditionMeterChoiceTypeJsonConverter))]
    public enum SelectValueFieldChoiceConditionMeterChoiceType
    {
        Choice,
    }
    public class SelectValueFieldChoiceConditionMeterChoiceTypeJsonConverter : JsonConverter<SelectValueFieldChoiceConditionMeterChoiceType>
    {
        public override SelectValueFieldChoiceConditionMeterChoiceType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string value = JsonSerializer.Deserialize<string>(ref reader, options);
            switch (value)
            {
                case "choice":
                    return SelectValueFieldChoiceConditionMeterChoiceType.Choice;
                default:
                    throw new ArgumentException(String.Format("Bad SelectValueFieldChoiceConditionMeterChoiceType value: {0}", value));
            }
        }

        public override void Write(Utf8JsonWriter writer, SelectValueFieldChoiceConditionMeterChoiceType value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case SelectValueFieldChoiceConditionMeterChoiceType.Choice:
                    JsonSerializer.Serialize<string>(writer, "choice", options);
                    return;
            }
        }
    }
}
