// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Datasworn
{
    /// <summary>
    /// Describes changes/additions made to the enhanced move's trigger
    /// conditions.
    /// </summary>
    public class TriggerSpecialTrackEnhancement
    {
        /// <summary>
        /// Trigger conditions added to the enhanced move.
        /// </summary>
        [JsonPropertyName("conditions")]
        public IList<TriggerSpecialTrackConditionEnhancement> Conditions { get; set; }
    }
}
